#!/usr/bin/python

# ratsbane@gmail.com 2007-05-23

import urllib2, os, time


# refer to http://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download/

aircraft_registration_url='http://registry.faa.gov/database/ReleasableAircraft.zip';

print aircraft_registration_url

local_aircraft_registration_archive=time.strftime('/var/aircraft/%Y')

if not os.path.isdir(local_aircraft_registration_archive):
	os.mkdir(local_aircraft_registration_archive)

# Try to get file
f = urllib2.urlopen(aircraft_registration_url)
aircraft_registrations = f.read()
f.close()

fout=file(local_aircraft_registration_archive+'/'+time.strftime('%Y-%m-%d_%H_%M_%S'), 'wb')
fout.write(aircraft_registrations)
fout.close()
time.sleep(10)

# Load files into SQL
import subprocess

exitcode = subprocess.call(['/var/aircraft/bin/load', time.strftime('%Y-%m-%d')] )

exitcode = subprocess.call(['/var/aircraft/bin/load_history'] )


