#!/usr/bin/python

# ratsbane@gmail.com 2007-05-23

import urllib2, os, time


# refer to http://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download/

# Define where we shall get the registration file and where we shall put it.
#aircraft_registration_url=time.strftime('http://registry.faa.gov/database/AR%m%Y.zip')
aircraft_registration_url='http://registry.faa.gov/database/ReleasableAircraft.zip';

print aircraft_registration_url

local_aircraft_registration_archive=time.strftime('/var/aircraft/%Y')
if not os.path.isdir(local_aircraft_registration_archive):
	os.mkdir(local_aircraft_registration_archive)

# Try to get file
f = urllib2.urlopen(aircraft_registration_url)
aircraft_registrations = f.read()
f.close()

fout=file(local_aircraft_registration_archive+'/'+time.strftime('%Y-%m-%d_%H_%M_%S'), 'wb')
fout.write(aircraft_registrations)
fout.close

# Copy files to catsmeat for processing
#import subprocess
#exitcode = subprocess.call(['rsync', '-ravz', local_aircraft_registration_archive, 'catsmeat:/home/doug/aircraft_registrations/data/'])

