#!/usr/bin/perl

use Test::Simple tests=>10;

use lib '.';
use FileSet;
$| = 1;  # autoflush print

my $fs = FileSet->new();

ok(defined $fs && ref $fs eq 'FileSet', 'new creates instance');

ok($#{$fs->{all}}>100, 'all_files gets a list of files');

ok($fs->{all}->[1] eq '/var/aircraft/2007/2007-05-23_23_45_20', 'all_files gets the first filename');

ok($fs->{all}->[14] eq '/var/aircraft/2007/2007-09-10_08_27_16', 'all_files correctly skips the first defective file');

my $r = $fs->_copy_and_unzip_file_into_temp('/var/aircraft/2007/2007-05-23_23_45_20');

ok( $r, 'copying and unzipping returned true for valid file');

ok(-e '/var/aircraft/temp/2007-05-23.zip', 'unzip got the correct date');

ok(-e '/var/aircraft/temp/MASTER.txt', "MASTER.txt file IS there when it should be");

my $r = $fs->_copy_and_unzip_file_into_temp('/var/aircraft/2007/2007-09-03_10_00_02');
 
ok( ! $r, 'copying and unzipping returned false for invalid file');

ok( ! -e '/var/aircraft/temp/MASTER.txt', "MASTER.txt file is NOT there when it shouldn't be");

$fs->{'current_file_index'}=1;
($data, $date) = $fs->_load_file();

ok( $date eq '2007-05-23', 'load_file returns the correct date');


