#!/usr/bin/perl

use Test::Simple tests=>9;

use lib '.';
use FileSet;

my $fs = FileSet->new();

ok(defined $fs && ref $fs eq 'FileSet', 'new creates instance');

ok($#{$fs->{all}}>100, 'all_files gets a list of files');

ok($fs->{all}->[0] eq '/var/aircraft/2007/2007-05-23_23_45_20', 'all_files gets the first filename');

ok($fs->{all}->[13] eq '/var/aircraft/2007/2007-09-10_08_27_16', 'all_files correctly skips the first defective file');

my $r = $fs->copy_and_unzip_file_into_temp('/var/aircraft/2007/2007-05-23_23_45_20');

ok( $r, 'copying and unzipping returned true for valid file');

ok(-e '/var/aircraft/temp/2007-05-23.zip', 'unzip got the correct date');

ok(-e '/var/aircraft/temp/MASTER.txt', 'MASTER.txt file is there');

my $r = $fs->copy_and_unzip_file_into_temp('/var/aircraft/2007/2007-09-03_10_00_02');
 
ok( ! $r, 'copying and unzipping returned false for invalid file');

ok( ! -e '/var/aircraft/temp/MASTER.txt', 'MASTER.txt file is not there');



#(undef, $d) = $fs->get_first();
#die "\n\nHEYYY \$d is $d\n";
#ok( $d eq '', 'get_first returns the correct date');




#(undef, $x) = $fs->get_first();
#print "$x\n";


#for (0..14) {print$fs->{all}->[$_]."\n";}

